### PR TITLE
Stop generating CldVideoPlayer ID using Math.random.

### LINKED ISSUE #281: [Bug] Stop generating CldVideoPLayer ID using Math.random
# **Bug Report**

## **Describe the bug**

Stop generating CldVideoPLayer ID using Math.random

Creating issues between server and client

Can we add a warning instead? Perhaps we would need to track the IDs being used in a top level scoped object?

## **Steps To Reproduce the error**

1.
2.
3.
4.

### **Your environment**

- OS: 
- Node version:
- Npm version:
- Browser name and version:

### PR DESCRIPTION
**Pull request by JoshuaRotimi**
# Description

- Removed the `idRef` generated with Math.random.
- Generate a Player ID using the public id or the `id` provided through the props. 
- Throw a console warning when two or more instances of the same video are identified stating to the user to provide a unique id for each video. 
- Add types of `showLogo`, `logoImageUrl`,  `logoOnclickUrl` for the logo object to the `CloudinaryVideoPlayerOptions` interface.  

## Issue Ticket Number
 #281

Fixes #<ISSUE_NUMBER>
Fixes #281

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist

- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have created an [issue](https://github.com/colbyfayock/next-cloudinary/issues) ticket for this PR
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/colbyfayock/next-cloudinary/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have run tests locally to ensure they all pass
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @JoshuaRotimi this generally looks great! i was testing this out locally though and check this out

image

my theory right now is because the page is rendered twice, it ends up seeing the same ID twice on the second render, incorrectly warning 🤔 

trying to think about how we could solve this. a useEffect where in the return function, removing the key from the object could work, but it seems unnecessary.

any ideas?

**Comment by JoshuaRotimi** [comment]
> hey @JoshuaRotimi this generally looks great! i was testing this out locally though and check this out
> 
> image
> my theory right now is because the page is rendered twice, it ends up seeing the same ID twice on the second render, incorrectly warning 🤔
> 
> trying to think about how we could solve this. a useEffect where in the return function, removing the key from the object could work, but it seems unnecessary.
> 
> theoretically, we could do something similar, but the useEffect just states whether the component has mounted / rendered for the first time, and only checks the ID mismatch during that first render?
> 
> any ideas?

Hmm I saw that. But I thought it might be happening because the component renders twice in dev mode. But now that you mention it, I see that the user might also have same experience in their dev mode. 

I think a possible solution might be to make `playerInstance` an array instead. Then make the `if` condition check if the array has two of the same `ids` in it. Then we can be certain that two components are being rendered with the same `id` and throw that warning. It should resolve the issue without needing a `useEffect`. What do you think?

**Comment by colbyfayock** [comment]
my initial thought is we would still see the same issue, if it renders twice with only 1 component with 1 ID, it would still have 2 instance in there right? but worth a try and seeing if it fixes it!

**Comment by JoshuaRotimi** [comment]
Yeah I'll make the update now and you can check it out.

**Comment by colbyfayock** [comment]
this seems to work great! i added a commit to add the IDs to the players on the examples page, a few were broken towards the bottom, but with the proper IDs they work great!

**Comment by colbyfayock** [comment]
@all-contributors please add @JoshuaRotimi for code

**Comment by colbyfayock** [comment]
@JoshuaRotimi congrats on the merged PR! since it's officially October, you've always qualified for Hacktoberfest swag! please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your github username and a link to your contribution where I'll follow up to request more information for getting you your swag

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
