### PR TITLE
Fix "gravity" is read-only

### PR DESCRIPTION
**Pull request by codingis4noobs2**
## Description

Fix "gravity" is read-only
---
## Issue Ticket Number
Fixes [Issue #29 ]

---
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have created an [issue](https://github.com/colbyfayock/next-cloudinary/issues) ticket for this PR
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/colbyfayock/next-cloudinary/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have run tests locally to ensure they all pass
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by colbyfayock** [comment]
hi @codingis4noobs2  thanks for the PR but this issue was already assigned to someone else inside https://github.com/colbyfayock/next-cloudinary/issues/29

they're already working on it in a separate PR https://github.com/colbyfayock/next-cloudinary/pull/31

**Comment by codingis4noobs2** [comment]
@colbyfayock i know, but he hasn't submitted it yet that's why i made a pull request 🙏

**Comment by colbyfayock** [comment]
hey @codingis4noobs2 change works, can you please add a quick test for this and we can get it moved in?

you'll need to create a new test file under next-cloudinary/tests/plugins/cropping.spec.js

**Comment by codingis4noobs2** [comment]
@colbyfayock Sure, i'll give it a shot 😀

**Comment by colbyfayock** [comment]
try using this as an example for writing a test https://github.com/colbyfayock/next-cloudinary/blob/main/next-cloudinary/tests/plugins/raw-transformations.spec.js

additionally note the filename convention

**Comment by codingis4noobs2** [comment]
@colbyfayock pls have a look now!!

**Comment by codingis4noobs2** [comment]
@colbyfayock ig there are no instructions for running this locally, if you could provide it, It would be great

**Comment by colbyfayock** [comment]
- check out the project
- run `yarn install` at the root of the project
- navigate into `next-cloudinary`
- run `yarn test`

**Comment by codingis4noobs2** [comment]
@colbyfayock ok thx 😀

**Comment by codingis4noobs2** [comment]
It will work now :)

**Comment by colbyfayock** [comment]
awesome 💪  thanks for the patience. i gtta update the contributing / working locally docs

**Comment by colbyfayock** [comment]
thanks @codingis4noobs2 nice work

email me at hello@colbyfayock.com where i'll send you a form to claim for free swag https://spacejelly.dev/hacktoberfest/

**Comment by colbyfayock** [comment]
@all-contributors please add @codingis4noobs2 for code, test

**Pull request merged**
