### PR TITLE
next/future/image

### PR DESCRIPTION
**Pull request by colbyfayock**

### CODE REVIEW

**Comment by colbyfayock** [comment]
https://github.com/all-contributors please add @colbyfayock for code, doc, example

**Comment by colbyfayock** [comment]
@all-contributors please add @colbyfayock for code, doc, example

**Comment by nucliweb** [comment]
What do you think about defining a prop to use `next/future/image` or `next/image`.
There are a lot of legacy projects with the `next/image` still.

**Comment by nucliweb** [comment]
Yes, but if I want to use `CldImage` component but I don't have the Next.js version lower than 12.3 (with support to `next/future/image`) I will have a crash, right?

**Comment by colbyfayock** [comment]
i need to test that theory and see (or if you want to help out with that). its my understanding `next/future/image` will be updated to `next/image` in the release, it won't maintain `/future` so it will treat it the same, it will just have a different API

i have Next.js as a peer dependency, so there shoudln't be any version requirements iif im not mistaken

**Comment by nucliweb** [comment]
@colbyfayock FYI, [Next.js 13](https://nextjs.org/blog/next-13#nextimage) will be remove `/future` from the component name.

**Pull request merged**
